# Try to find LibArchive
# NOTE: The FindLibArchive.cmake included with CMake has no support for static libraries.
# Instead we use PkgConfig generated by LibArchive to import
#
# This module exposes
# LibArchive_FOUND, LibArchive_VERSION, LibArchive_PREFIX
# LibArchive_INCLUDE_DIR, LibArchive_LIBDIR
# LibArchive_LIBRARIES, LibArchive_LINK_LIBRARIES, LibArchive_LIBRARY_DIRS

set(libarchive_LIBNAME "archive")

include(cmake/Modules/FindLibraryDependencies.cmake)
file(REAL_PATH "${CMAKE_SOURCE_DIR}/../../build/deps/core/lib${libarchive_LIBNAME}-install/lib/pkgconfig/"
        libarchive_PKGCONFIG_ABS_PATH)
set(ENV{PKG_CONFIG_PATH} "${libarchive_PKGCONFIG_ABS_PATH};$ENV{PKG_CONFIG_PATH}")

find_package(PkgConfig)
pkg_search_module(LibArchive QUIET REQUIRED IMPORTED_TARGET GLOBAL "lib${libarchive_LIBNAME}")

message(STATUS "### LibArchive_LIBRARIES ${LibArchive_LIBRARIES}")
message(STATUS "### LibArchive_LINK_LIBRARIES ${LibArchive_LINK_LIBRARIES}")
message(STATUS "### LibArchive_LIBRARY_DIRS ${LibArchive_LIBRARY_DIRS}")
message(STATUS "### LibArchive_INCLUDE_DIR ${LibArchive_INCLUDE_DIR}")
message(STATUS "### LibArchive_LIBDIR ${LibArchive_LIBDIR}")
