"""
Generates the tokenizer.onnx for bge-small-en-v1.5 from the HuggingFace tokenizer.

The OnnxEmbedder uses a two-model architecture:
  1. tokenizer.onnx  - BertTokenizer custom op (generated by this script)
  2. encoder.onnx    - transformer encoder (downloaded directly from HuggingFace)

Usage:
    python prepare_bge_model.py --output-dir <output-path>

Prerequisites:
    pip install onnx onnxruntime-extensions transformers

The script downloads the tokenizer config from HuggingFace and generates
tokenizer.onnx using onnxruntime-extensions' BertTokenizer custom op.
"""

import argparse
import sys
from pathlib import Path

import onnx


def generate_tokenizer_onnx(output_dir: str) -> Path:
    """Generate tokenizer.onnx from the HuggingFace tokenizer."""
    from onnxruntime_extensions import gen_processing_models
    from transformers import AutoTokenizer

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    tokenizer_onnx_path = output_path / "tokenizer.onnx"

    print("Loading HuggingFace tokenizer for BAAI/bge-small-en-v1.5...")
    tokenizer = AutoTokenizer.from_pretrained("BAAI/bge-small-en-v1.5")

    print("Generating tokenizer.onnx with BertTokenizer custom op...")
    pre_model, _ = gen_processing_models(tokenizer, pre_kwargs={})
    onnx.save(pre_model, str(tokenizer_onnx_path))

    print(f"Saved tokenizer.onnx ({tokenizer_onnx_path.stat().st_size / 1024:.1f} KB)")
    return tokenizer_onnx_path


def verify_tokenizer(tokenizer_path: Path) -> bool:
    """Verify the tokenizer.onnx works correctly."""
    import numpy as np
    import onnxruntime as ort
    from onnxruntime_extensions import get_library_path

    so = ort.SessionOptions()
    so.register_custom_ops_library(get_library_path())
    session = ort.InferenceSession(str(tokenizer_path), so)

    test_input = np.array(["test sentence"])
    outputs = session.run(None, {"text": test_input})

    print(f"Tokenizer inputs:  {[i.name for i in session.get_inputs()]}")
    print(f"Tokenizer outputs: {[o.name for o in session.get_outputs()]}")
    print(f"Token count for 'test sentence': {len(outputs[0])}")
    return len(outputs[0]) > 0


def main():
    parser = argparse.ArgumentParser(
        description="Generate tokenizer.onnx for bge-small-en-v1.5"
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory to write tokenizer.onnx",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify the generated tokenizer works",
    )
    args = parser.parse_args()

    tokenizer_path = generate_tokenizer_onnx(args.output_dir)

    if args.verify:
        print("\nVerifying tokenizer.onnx...")
        if verify_tokenizer(tokenizer_path):
            print("Verification passed.")
        else:
            print("Verification FAILED.", file=sys.stderr)
            sys.exit(1)

    print(f"\nDone. Place the following files in your --semantic-model-dir:")
    print(f"  1. {tokenizer_path}  (generated above)")
    print(f"  2. encoder.onnx      (download from HuggingFace BAAI/bge-small-en-v1.5)")
    print(f"  3. libortextensions.so (built from onnxruntime-extensions)")


if __name__ == "__main__":
    main()
