//! Projected KV-IR search.
//!
//! ABI v1 exposes KV-IR as a serializer and a raw pull deserializer: it can decode a stream but
//! cannot filter one, so a caller wanting the events matching a query had to decode every event
//! and evaluate the query itself. This module runs the engine's own KV-IR search and returns typed
//! values for the requested paths, mirroring what [`crate::columnar`] does for archives.
//!
//! A KV-IR stream has no table structure to resume from, and its schema is discovered as the
//! stream is read, so the search runs to completion when the scanner opens and its matches are
//! buffered. That is bounded in practice because a caller scans one closed segment at a time, and
//! a segment is small by construction.

use std::fs::File;
use std::path::Path;

use clp_s::ingest::{KvIrNamespace, KvIrOptions, KvIrReader, KvIrValueKind};
use clp_s::search::{
    KvIrMatchedEvent, KvIrSearchLimits, KvIrSearchOptions, KvIrSearchSink, ParsedQuery,
    search_first_kv_ir_stream,
};

use crate::columnar::{Cell, ScanError, kind};

/// Splits an escaped dot descriptor into its components.
fn split_descriptor(source: &str) -> Vec<String> {
    let mut components = Vec::new();
    let mut current = String::new();
    let mut escaped = false;
    for character in source.chars() {
        if escaped {
            current.push(character);
            escaped = false;
        } else if '\\' == character {
            escaped = true;
        } else if '.' == character {
            components.push(std::mem::take(&mut current));
        } else {
            current.push(character);
        }
    }
    components.push(current);
    components
}

/// Resolves one path against a namespace's retained schema, returning every node that can carry a
/// value for it.
///
/// A KV-IR schema is discovered as the stream is read, so this is resolved per matched event
/// rather than once: an event may be the first to introduce the node a path names.
fn resolve<'a>(
    event: KvIrMatchedEvent<'a>,
    namespace: KvIrNamespace,
    components: &[String],
) -> Vec<usize> {
    let schema = event.schema(namespace);
    let mut current: Vec<usize> = schema
        .iter()
        .enumerate()
        .filter(|(index, node)| node.parent_id() == *index)
        .map(|(index, _)| index)
        .collect();
    if current.is_empty() {
        // A root is conventionally its own parent; fall back to node 0 when that does not hold.
        current = vec![0];
    }
    for (depth, component) in components.iter().enumerate() {
        let last = depth + 1 == components.len();
        let mut next = Vec::new();
        for parent in &current {
            let Some(node) = schema.get(*parent) else {
                continue;
            };
            for child_id in node.child_ids() {
                let Some(child) = schema.get(*child_id) else {
                    continue;
                };
                if child.key() != component.as_bytes() {
                    continue;
                }
                next.push(*child_id);
            }
        }
        if next.is_empty() {
            return Vec::new();
        }
        if last {
            return next;
        }
        current = next;
    }
    Vec::new()
}

/// Reads one requested path out of a matched event.
fn project_field(event: KvIrMatchedEvent<'_>, components: &[String], text: &mut Vec<u8>) -> Cell {
    for namespace in [KvIrNamespace::UserGenerated, KvIrNamespace::AutoGenerated] {
        for node_id in resolve(event, namespace, components) {
            let Some(pair) = event.pair(namespace, node_id) else {
                continue;
            };
            return match pair.value().kind() {
                KvIrValueKind::Integer(value) => Cell {
                    kind: kind::INTEGER,
                    integer: value.value(),
                    real: 0.0,
                    text_offset: 0,
                    text_length: 0,
                },
                KvIrValueKind::Float { bits } => Cell {
                    kind: kind::FLOAT,
                    integer: 0,
                    real: f64::from_bits(bits),
                    text_offset: 0,
                    text_length: 0,
                },
                KvIrValueKind::Boolean(value) => Cell {
                    kind: kind::BOOLEAN,
                    integer: i64::from(value),
                    real: 0.0,
                    text_offset: 0,
                    text_length: 0,
                },
                KvIrValueKind::String(bytes) => {
                    let start = text.len();
                    text.extend_from_slice(bytes);
                    Cell {
                        kind: kind::STRING,
                        integer: 0,
                        real: 0.0,
                        text_offset: start,
                        text_length: bytes.len(),
                    }
                }
                // A CLP-encoded string needs its logtype and variables recombined, which this ABI
                // does not surface. Reporting it unsupported keeps ABSENT meaning "no such path".
                KvIrValueKind::EncodedText(_) => Cell {
                    kind: kind::UNSUPPORTED,
                    integer: 0,
                    real: 0.0,
                    text_offset: 0,
                    text_length: 0,
                },
                // An explicit null and an empty object are both present-but-not-scalar, which the
                // caller renders as SQL NULL exactly as a missing path would be.
                KvIrValueKind::Null | KvIrValueKind::EmptyObject => Cell {
                    kind: kind::ABSENT,
                    integer: 0,
                    real: 0.0,
                    text_offset: 0,
                    text_length: 0,
                },
                // KvIrValueKind is non-exhaustive. A variant added upstream reports unsupported
                // rather than absent, so a new value type cannot read as a missing path.
                _ => Cell {
                    kind: kind::UNSUPPORTED,
                    integer: 0,
                    real: 0.0,
                    text_offset: 0,
                    text_length: 0,
                },
            };
        }
    }
    Cell {
        kind: kind::ABSENT,
        integer: 0,
        real: 0.0,
        text_offset: 0,
        text_length: 0,
    }
}

/// A projected scan over one KV-IR stream.
pub(crate) struct KvIrProjectedScanner {
    field_count: usize,
    cells: Vec<Cell>,
    text: Vec<u8>,
    emit_cursor: usize,
    rows: usize,
}

impl KvIrProjectedScanner {
    pub(crate) fn open(
        path: &Path,
        query: &ParsedQuery,
        ignore_case: bool,
        fields: &[String],
    ) -> Result<Self, ScanError> {
        let components: Vec<Vec<String>> = fields.iter().map(|f| split_descriptor(f)).collect();
        let field_count = fields.len();
        let mut cells = Vec::new();
        let mut text = Vec::new();
        let mut rows = 0_usize;

        let file = File::open(path).map_err(|source| {
            ScanError::Archive(format!("failed to open {}: {source}", path.display()))
        })?;
        let decoder = zstd::stream::read::Decoder::new(file).map_err(|source| {
            ScanError::Archive(format!("failed to open {}: {source}", path.display()))
        })?;

        {
            let sink = |event: KvIrMatchedEvent<'_>| -> Result<(), ScanError> {
                for path_components in &components {
                    let cell = project_field(event, path_components, &mut text);
                    cells.push(cell);
                }
                rows += 1;
                Ok(())
            };
            let mut searcher = KvIrSearchSink::new(
                query,
                sink,
                KvIrSearchOptions::new(ignore_case, KvIrSearchLimits::default()),
            )
            .map_err(|source| {
                ScanError::Archive(format!("failed to compile KV-IR query: {source}"))
            })?;
            let mut reader = KvIrReader::new(decoder, KvIrOptions::default());
            if let Err(error) = search_first_kv_ir_stream(&mut reader, &mut searcher) {
                // A stream still being appended to has no end marker. The rows before the
                // truncation are complete and are kept, which is what a live-ingest reader needs.
                if 0 == reader.stats().streams() {
                    return Err(ScanError::Archive(format!(
                        "failed to search {}: {error}",
                        path.display()
                    )));
                }
            }
        }

        Ok(Self {
            field_count,
            cells,
            text,
            emit_cursor: 0,
            rows,
        })
    }

    /// Returns the next matched row's cells, or `None` once the stream is exhausted.
    pub(crate) fn next_row(&mut self) -> Option<(&[Cell], &[u8])> {
        if self.emit_cursor >= self.rows {
            return None;
        }
        let start = self.emit_cursor * self.field_count;
        let end = start + self.field_count;
        self.emit_cursor += 1;
        Some((&self.cells[start..end], &self.text))
    }
}
